// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvLAysrO3XsPlxI409XEFzmSSqieqH1U',
    appId: '1:1051905371406:web:9602580022090abb1a3b5f',
    messagingSenderId: '1051905371406',
    projectId: 'plataformalsu-bd176',
    authDomain: 'plataformalsu-bd176.firebaseapp.com',
    storageBucket: 'plataformalsu-bd176.appspot.com',
    measurementId: 'G-GVDQ6NQ78L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUL-bAwM-0cJuOXRAWE4bLFuxH2XizzrI',
    appId: '1:1051905371406:android:3cf90cc67de4cf911a3b5f',
    messagingSenderId: '1051905371406',
    projectId: 'plataformalsu-bd176',
    storageBucket: 'plataformalsu-bd176.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIKoEoaw5X9i2gggciTBgy9Msi6Ka6i8',
    appId: '1:1051905371406:ios:1a6cdaa879d828321a3b5f',
    messagingSenderId: '1051905371406',
    projectId: 'plataformalsu-bd176',
    storageBucket: 'plataformalsu-bd176.appspot.com',
    androidClientId: '1051905371406-capsn6b4h69r4gepl3ct9fgcv0pk4d1e.apps.googleusercontent.com',
    iosBundleId: 'uy.maf.com.plataformalsuios',
  );
}
